// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgSZFgXQ8eHPd4etoCa-os15f178Nrlt4',
    appId: '1:444334588711:web:8a67473b3c196f45e75f02',
    messagingSenderId: '444334588711',
    projectId: 'todotick-f0b76',
    authDomain: 'todotick-f0b76.firebaseapp.com',
    storageBucket: 'todotick-f0b76.firebasestorage.app',
    measurementId: 'G-V4TP1JL6KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Kgo2Ahl2Q3EC8rHtcZ9VCqm2bwYw_20',
    appId: '1:444334588711:android:e48203dc707da8f4e75f02',
    messagingSenderId: '444334588711',
    projectId: 'todotick-f0b76',
    storageBucket: 'todotick-f0b76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHi9V1NYhZ4nWUDktg_N6l_l42uMB-uMs',
    appId: '1:444334588711:ios:5735156de03cfa0ae75f02',
    messagingSenderId: '444334588711',
    projectId: 'todotick-f0b76',
    storageBucket: 'todotick-f0b76.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHi9V1NYhZ4nWUDktg_N6l_l42uMB-uMs',
    appId: '1:444334588711:ios:5735156de03cfa0ae75f02',
    messagingSenderId: '444334588711',
    projectId: 'todotick-f0b76',
    storageBucket: 'todotick-f0b76.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgSZFgXQ8eHPd4etoCa-os15f178Nrlt4',
    appId: '1:444334588711:web:530d69fe777025eee75f02',
    messagingSenderId: '444334588711',
    projectId: 'todotick-f0b76',
    authDomain: 'todotick-f0b76.firebaseapp.com',
    storageBucket: 'todotick-f0b76.firebasestorage.app',
    measurementId: 'G-H70LKE2TQX',
  );
}
